Final

Lecture 15 - NumPy

In [34]:
import numpy as np

In [35]:
height=[1.65, 1.70, 1.75, 1.80]
weight=[60.50, 65.75, 70.33, 75.50]

np_height=np.array(height)
np_weight=np.array(weight)

bmi_list=np_weight/np_height**2

print(bmi_list)

[22.22222222 22.75086505 22.96489796 23.30246914]


In [36]:
zeros_arr=np.zeros((3, 3))
print(zeros_arr)

ones_arr=np.ones((2, 4))
print(ones_arr)

random_arr=np.random.randint(10, size=(2, 3))
print(random_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4 7 3]
 [5 3 8]]


In [37]:
arr1=np.array([1, 2, 3])
arr2=np.array([4, 5, 6])

result=arr1+arr2
print(result)

result=np.dot(arr1, arr2)
print(result)

arr3=np.array([[1, 2], [3, 4]])
transposed_arr=arr3.T
print(transposed_arr)

[5 7 9]
32
[[1 3]
 [2 4]]


In [38]:
arr=np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

print(arr[1, 2])
print(arr[0, :])
print(arr[:, 3])
print(arr[1:3, 1:4])

7
[1 2 3 4]
[ 4  8 12]
[[ 6  7  8]
 [10 11 12]]


In [39]:
birth_rates=np.array([1.24, 1.30, 1.19, 1.21, 1.24, 1.17, 1.05, 0.98, 0.92, 0.84, 0.81, 0.78])

mean=np.mean(birth_rates)
median=np.median(birth_rates)
max_value=np.max(birth_rates)
min_value=np.min(birth_rates)
std_dev=np.std(birth_rates)
variance=np.var(birth_rates)

print(birth_rates)
print(mean)
print(median)
print(max_value)
print(min_value)
print(std_dev)
print(variance)

[1.24 1.3  1.19 1.21 1.24 1.17 1.05 0.98 0.92 0.84 0.81 0.78]
1.0608333333333333
1.1099999999999999
1.3
0.78
0.18011377577026755
0.03244097222222222


In [40]:
class Stack:
    def __init__(self, size):
        self.size=size
        self.stack=np.empty(size, dtype=np.object_) # np.object? np.object_?
        self.top=-1

    def is_empty(self):
        return self.top==-1
    
    def is_full(self):
        return self.top==self.size-1
    
    def push(self, element):
        if self.is_full():
            print("Stack is full.")
        else:
            self.top+=1
            self.stack[self.top]=element

    def pop(self):
        if self.is_empty():
            print("Stack is empty.")
        else:
            element=self.stack[self.top]
            self.stack[self.top]=None
            self.top-=1
            return element
        
    def peek(self):
        if self.is_empty():
            print("Stack is empty.")
        else:
            return self.stack[self.top]
        
stack=Stack(5)
stack.push(10)
stack.push(20)
stack.push(30)
stack.push(40)
print(stack.pop())
print(stack.peek())

40
30


In [41]:
scores=np.array([[80, 90, 60],
                [75, 80, 90],
                [90, 95, 65],
                [99, 70, 70]])

weightings=np.array([[3, 1],
                     [3, 8],
                     [4, 1]])

result=np.matmul(scores, weightings)

for i, student_result in enumerate(result):
    print(i+1, student_result)

1 [750 860]
2 [825 805]
3 [815 915]
4 [787 729]


Lecture 16 - Pandas

In [42]:
import pandas as pd
import random

In [43]:
data=[10, 20, 30, 40, 50]

series=pd.Series(data)

print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [44]:
scores=pd.Series([85, 92, 78, 90, 88])

print(scores)
print(scores[0])
print(scores[2])
print(scores.min())
print(scores.max())
print(scores.mean())
print(scores[scores>=90].index)

0    85
1    92
2    78
3    90
4    88
dtype: int64
85
78
78
92
86.6
Index([1, 3], dtype='int64')


In [45]:
class Stack:
    def __init__(self):
        self.stack=pd.Series(dtype='object')

    def push(self, value):
        self.stack=pd.concat([self.stack, pd.Series([value])], ignore_index=True)

    def pop(self):
        if self.is_empty():
            print("Stack is empty.")
            return None
        popped_item=self.stack.iloc[-1]
        self.stack=self.stack.iloc[:-1]
        return popped_item
    
    def is_empty(self):
        # return len(self.stack)==0
        return self.stack.empty
    
    def peek(self):
        if self.is_empty():
            print("Stack is empty.")
            return None
        else:
            return self.stack.iloc[-1]
        
    def size(self):
        return len(self.stack)
    
stack=Stack()
stack.push(10)
stack.push(20)
stack.push(30)
print(stack.size())
print(stack.peek())
print(stack.stack)
print(stack.pop())
print(stack.stack)
print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.pop())

3
30
0    10
1    20
2    30
dtype: int64
30
0    10
1    20
dtype: int64
20
10
Stack is empty.
None
Stack is empty.
None


C:\Users\jkpxt\AppData\Local\Temp\ipykernel_5668\3557382488.py:6: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  self.stack=pd.concat([self.stack, pd.Series([value])], ignore_index=True)


In [46]:
data={
    "Name": ["John", "Emma", "Liam", "Olivia", "Noah"],
    "Age": [25, 28, 24, 27, 26],
    "Score": [85, 92, 78, 90, 88]
}

df=pd.DataFrame(data)
print(df)
print()
print(df.head(3))
print()
print(df.describe())
print()
print(df.shape)
print()
print(df.columns)
print()
print(df.index)
print()
print(df.loc[2:3, "Name":"Score"])
print()
print(df.sort_values("Score", ascending=False))
print()
print(df)
print()

     Name  Age  Score
0    John   25     85
1    Emma   28     92
2    Liam   24     78
3  Olivia   27     90
4    Noah   26     88

   Name  Age  Score
0  John   25     85
1  Emma   28     92
2  Liam   24     78

             Age      Score
count   5.000000   5.000000
mean   26.000000  86.600000
std     1.581139   5.458938
min    24.000000  78.000000
25%    25.000000  85.000000
50%    26.000000  88.000000
75%    27.000000  90.000000
max    28.000000  92.000000

(5, 3)

Index(['Name', 'Age', 'Score'], dtype='object')

RangeIndex(start=0, stop=5, step=1)

     Name  Age  Score
2    Liam   24     78
3  Olivia   27     90

     Name  Age  Score
1    Emma   28     92
3  Olivia   27     90
4    Noah   26     88
0    John   25     85
2    Liam   24     78

     Name  Age  Score
0    John   25     85
1    Emma   28     92
2    Liam   24     78
3  Olivia   27     90
4    Noah   26     88



In [48]:
departments=["Comp", "Chem", "Life", "Semi"]
student_ids=[202301, 202302, 202303, 202304]
names=["S1", "S2", "S3", "S4"]
subjects=["Programming", "Calculus", "Physics", "Chemistry"]

data=[]

for i in range(len(names)):
    scores=[random.randint(80, 100) for _ in range(len(subjects))]
    grades=[]
    for score in scores:
        if score>=90:
            grades.append("A")
        elif score>=80:
            grades.append("B")
        elif score>=70:
            grades.append("C")
        else:
            grades.append("F")

    for j in range(len(subjects)):
        data.append([departments[i], student_ids[i], names[i], subjects[j], scores[j], grades[j]])

df=pd.DataFrame(data, columns=["Department", "Student ID", "Name", "Subject", "Score", "Grade"])
print(df)

   Department  Student ID Name      Subject  Score Grade
0        Comp      202301   S1  Programming     96     A
1        Comp      202301   S1     Calculus     91     A
2        Comp      202301   S1      Physics     91     A
3        Comp      202301   S1    Chemistry     80     B
4        Chem      202302   S2  Programming     80     B
5        Chem      202302   S2     Calculus     96     A
6        Chem      202302   S2      Physics     98     A
7        Chem      202302   S2    Chemistry     87     B
8        Life      202303   S3  Programming     98     A
9        Life      202303   S3     Calculus     87     B
10       Life      202303   S3      Physics     85     B
11       Life      202303   S3    Chemistry     80     B
12       Semi      202304   S4  Programming     81     B
13       Semi      202304   S4     Calculus     98     A
14       Semi      202304   S4      Physics     83     B
15       Semi      202304   S4    Chemistry     80     B


In [64]:
class StudentManagement:
    def __init__(self):
        self.df=pd.DataFrame(columns=["Student ID", "Name", "Department", "GPA"])
    
    def add_student(self, studentID, name, department, gpa):
        new_student=pd.DataFrame([{
            "Student ID": studentID,
            "Name": name,
            "Department": department,
            "GPA": gpa
        }])
        self.df=pd.concat([self.df, new_student], ignore_index=True)

    def remove_student(self, studentID):
        if studentID in self.df["Student ID"].values:
            self.df=self.df[self.df["Student ID"]!=studentID]
        else:
            print("Student doesn't exist.")

    def search_student(self, studentID):
        if studentID in self.df["Student ID"].values:
            student=self.df.loc[self.df["Student ID"]==studentID]
            print(student)
        else:
            print("Student doesn't exist.")

    def display_students(self):
        print(self.df)

studentManagement=StudentManagement()
studentManagement.add_student(202401, "S1", "Comp", 4.3)
studentManagement.add_student(202402, "S2", "Math", 4.3)
studentManagement.add_student(202403, "S3", "Physics", 4.3)
studentManagement.add_student(202404, "S4", "Chem", 4.3)

studentManagement.display_students()
print()
studentManagement.search_student(202402)
print()
studentManagement.remove_student(202403)
studentManagement.display_students()
print()

  Student ID Name Department  GPA
0     202401   S1       Comp  4.3
1     202402   S2       Math  4.3
2     202403   S3    Physics  4.3
3     202404   S4       Chem  4.3

  Student ID Name Department  GPA
1     202402   S2       Math  4.3

  Student ID Name Department  GPA
0     202401   S1       Comp  4.3
1     202402   S2       Math  4.3
3     202404   S4       Chem  4.3



C:\Users\jkpxt\AppData\Local\Temp\ipykernel_5668\233245363.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df=pd.concat([self.df, new_student], ignore_index=True)


In [69]:
student_scores=pd.DataFrame({
    "국어": [80, 75, 90, 99],
    "수학": [90, 80, 95, 70],
    "영어": [60, 85, 65, 70]
}, index=["김", "이", "박", "최"])

weights=pd.DataFrame({
    "우수반": [3, 3, 4],
    "수학반": [1, 4, 1]
}, index=["국어", "수학", "영어"])

result=student_scores.dot(weights)

print(result)

   우수반  수학반
김  750  500
이  805  480
박  815  535
최  787  449
