In [42]:
import numpy as np

In [43]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [44]:
print(type(a))

<class 'numpy.ndarray'>


In [45]:
print(np.array([[0, 1, 2],
                [3, 4, 5]]))

[[0 1 2]
 [3 4 5]]


In [46]:
print(np.zeros((3, 4), dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [47]:
print(np.ones((2, 3), dtype=int))
print()
print(np.array([[1., 1., 1.],
                [1., 1., 1.]]))

[[1 1 1]
 [1 1 1]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [48]:
a = np.arange(1, 13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
b=a.reshape((3, 4))
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
print(np.transpose(b))
print()
print(b.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [51]:
a = np.arange(1, 16)
b = a.reshape((3, 5))
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [52]:
print(b[1, 2])

8


In [53]:
print(b[1:, 3:])

[[ 9 10]
 [14 15]]


In [54]:
b[1:, 3:]=100
print(b)

[[  1   2   3   4   5]
 [  6   7   8 100 100]
 [ 11  12  13 100 100]]


In [55]:
c=b+10
print(c)

[[ 11  12  13  14  15]
 [ 16  17  18 110 110]
 [ 21  22  23 110 110]]


In [56]:
A=np.array([[1, 2],
            [3, 4]])
B=np.array([[5, 6],
            [7, 8]])

print(A+B)
print(A-B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [57]:
print(A@B)
print()
print(np.matmul(A, B))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [58]:
import numpy as np

n=int(input("3 이상의 정수 입력: "))

a=np.zeros((n, n))
print(a)
print()

a[1:n-1, 1:n-1]=1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
